# Generated by Django 3.2 on 2021-08-11 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('roll', models.IntegerField()),
                ('city', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=256)),
            ],
        ),
    ]
